main: it.loneliness.mc.automatihelper.Plugin
name: AutomaticHelper
version: 0.1
api-version: 1.20
depend: []
commands:
  automatichelper:
    description: Base command for MobRaid plugin
    usage: /<command> <subcommand>
    aliases: [ah]